[package]
name = "BINUSMAYA_Discord_Bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.7"
tokio = { version = "1" }
thirtyfour = {version = "0.27.2"}
serde_json = "1.0.73"
serde = "1.0.132"
serenity = "0.10"