[package]
name = "BINUSMAYA_Discord_Bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.7"
tokio = { version = "1", features = ["full"] }
thirtyfour = "0.22.0"
json = "0.12.4"